<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.7.4 setup script
 * Date: Mon, 16 Oct 2017 09:10:32 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: config-server [1] */
$i++;

/* End of servers configuration */
